Repository HelloYeew/maisim, pull requests merged in 2022-06, with the labels that each got.

#44 Add logic to make `Playfield` can spawn note from a target time
  maisim/maisim.Game.Tests/Visual/Component/Gameplay/TestSceneGameplayElement.cs
  maisim/maisim.Game.Tests/Visual/Screen/TestSceneNoteSpawnTimer.cs
  maisim/maisim.Game.Tests/Visual/Screen/TestScenePlayfieldScreen.cs
  maisim/maisim.Game/Component/Gameplay/Notes/DrawableBreakNote.cs
  maisim/maisim.Game/Component/Gameplay/Notes/DrawableNote.cs
  maisim/maisim.Game/Component/Gameplay/Notes/DrawableSlidePathNote.cs
  maisim/maisim.Game/Component/Gameplay/Notes/DrawableSlideStarNote.cs
  maisim/maisim.Game/Component/Gameplay/Notes/DrawableTapBothNote.cs
  maisim/maisim.Game/Component/Gameplay/Notes/DrawableTapNote.cs
  maisim/maisim.Game/Component/Gameplay/Notes/DrawableTouchHoldNote.cs
  maisim/maisim.Game/Component/Gameplay/Notes/DrawableTouchNote.cs
  maisim/maisim.Game/Screen/Gameplay/Playfield.cs
  maisim/maisim.Game/Screen/Gameplay/PlayfieldScreen.cs
Labels: area:gameplay, size/L

#81 Fix hole in condition in `CalculateRank` function
  maisim/maisim.Game/Scores/ScoreProcessor.cs
Labels: size/M, area:scoring

#92 Get rid of Maimai from readme
  README.md
Labels: size/S

#93 Change score in `TrackCard` to only show on 2 decimal point
  maisim/maisim.Game/Graphics/UserInterface/TrackCard.cs
  maisim/maisim.Game/Graphics/UserInterface/TrackCardFocused.cs
Labels: area:menu, size/XXL

#104 Update design to sync with figma
  maisim/maisim.Desktop/game.ico
  maisim/maisim.Game/Screen/BackgroundScreen.cs
  maisim/maisim.Game/Screen/MainMenuScreen.cs
  maisim/maisim.Resources/Textures/background.jpg
  maisim/maisim.Resources/Textures/background.png
  maisim/maisim.Resources/Textures/background2.png
  maisim/maisim.Resources/Textures/background3.jpg
Labels: area:user-interface, size/XS
